# Generated by Django 3.0.8 on 2020-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task name')),
                ('completed', models.BooleanField(default=False)),
                ('time_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
