# Generated by Django 3.0.8 on 2020-08-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(3, 'High'), (2, 'Mid'), (1, 'Low')], null=True),
        ),
    ]
